const movieActionTypes = {
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_FINISH: 'FETCH_MOVIES_FINISH',
  FETCH_MOVIES_FAIL: 'FETCH_MOVIES_FAIL',
  FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
  CLEAR_MOVIES: 'CLEAR_MOVIES',
  SET_SEARCH: 'SET_SEARCH',
  FETCH_REVIEWS_FAIL: 'FETCH_REVIEWS_FAIL',
  CLEAR_REVIEWS: 'CLEAR_REVIWS',
  SET_MOVIE_REVIEWS: 'SET_MOVIE_REVIEWS'
};

export default movieActionTypes;
